hw3_to_do/hw3_to_do/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('to_do.urls')),
    path('user/', include('user_app.urls')),
]

hw3_to_do/to_do/urls.py
from django.urls import path
from . import views
# from .views import Create


urlpatterns = [
    path('', views.home, name = 'home'),
    path('to_do_view/<str:pk>', views.to_do_view, name = 'to_do_view'),
    path('to_do_update/<str:pk>', views.to_do_update, name = 'to_do_update'),
    path('to_do_create/', views.to_do_create, name = 'to_do_create'),
    path('task_delete/<int:pk>', views.task_delete, name = 'task_delete'),
    # path('to_do_create/', Create.as_view(), name = 'to_do_create'),
]

hw3_to_do/user_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as user_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name = "login"),
    path('logoutbasic/',auth_views.LogoutView.as_view(), name="logoutbasic"),
    path('register/', user_views.user_register, name = "register"),
    path('profile/', user_views.profile, name = "profile"),
    path('user_logout/', user_views.user_logout, name = "user_logout"),
]

hw3_to_do/to_do/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

STATUS_CHOICES_N = (
	(0, "Allow"),
	(1, "Don't Allow"),
	)

STATUS_CHOICES_S = (
	(0, "New"),
	(1, "Doing"),
	(2, "Done"),
	)

class NewToDo(models.Model):
	name = models.CharField(max_length = 15)
	description = models.TextField()
	date_time = models.DateTimeField(default = timezone.now)
	notification = models.IntegerField(choices = STATUS_CHOICES_N, default = "0")
	status = models.IntegerField(choices = STATUS_CHOICES_S)
	user = models.ForeignKey(User, on_delete = models.CASCADE, default = 1)

	def __str__(self):
		return self.name

hw3_to_do/to_do/forms.py
from django.forms import ModelForm
from django import forms
from .models import NewToDo


class TaskForm(ModelForm):
	
	class Meta:
		model = NewToDo
		fields = '__all__'
		exclude = ['user']

hw3_to_do/user_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
	email = forms.EmailField(required = False)

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

hw3_to_do/to_do/views.py
from django.shortcuts import render, redirect
from .models import NewToDo
from .forms import TaskForm
# from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages



def home(request):
	if not request.user.is_authenticated:
		return render(request, 'to_do/welcome.html')
	else:
		tasks = NewToDo.objects.all().filter(user = request.user)
		context = {
					'tasks': tasks
				}
		return render(request, 'to_do/home.html', context)

def to_do_view(request, pk):
	task = NewToDo.objects.get(id = pk)
	context = {'task':task}
	return render(request, 'to_do/task_view.html', context)

	
@login_required(login_url = 'login')
def to_do_update(request, pk):
	task = NewToDo.objects.all().filter(id = pk)[0]

	if request.method == "POST":
		form = TaskForm(request.POST, instance = task)
		if form.is_valid():
			form.save()
			messages.add_message(request, messages.SUCCESS, "Content updated successfully.")
			return redirect("home")
	
	form = TaskForm(instance = task)

	context = {'form': form}

	return render(request, 'to_do/task_update.html', context)

# class Create(CreateView):
# 	model = NewToDo
# 	fields = ['name', 'description']

@login_required(login_url = 'login')
def to_do_create(request):

	if request.method == "POST":
		form = TaskForm(request.POST)
		if form.is_valid():
			task = form.save(commit = False)
			task.user = User.objects.get(id = request.user.id)
			task.save()
			messages.add_message(request, messages.SUCCESS, "Content created successfully.")
			return redirect("home")
	
	form = TaskForm()

	context = {'form': form}

	return render(request, 'to_do/new_task.html', context)

@login_required(login_url = 'login')
def task_delete(request, pk):
	task = NewToDo.objects.get(id=pk)

	task.delete()
	messages.add_message(request, messages.WARNING, "Content already don't exist.")
	return redirect('home')

hw3_to_do/user_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


def user_register(request):
    form = UserRegisterForm()
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')

            user = authenticate(request, username = username, password = password)

            if not user is None:
            	login(request, user)
            messages.add_message(request, messages.SUCCESS, "User is created successfully.")
            return redirect("home")
        else:
            messages.add_message(request, messages.WARNING, "User is not created successfully")
    return render(request, 'registration/user_register.html', {'form': form})


@login_required
def profile(request):
	return render(request, 'registration/profile.html')

def user_logout(request):
	return render(request, 'registration/logout.html')

hw3_to_do/to_do/templates/to_do/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To Do</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
	h3{
	color: #374d65;
	}

	body{
		background-color: #638CB8;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #6BA3E8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	.item-row{
		background-color: #374d65;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}
	a{
	color: white;
	}
	a:hover {
    color: white;
    }
    #sign_up{
        color: #337ab7;
        }
</style>

</head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">To DO</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'home' %}">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if not request.user.is_authenticated %}
          <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% else %}
            <li><a href="{% url 'profile' %}"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
            <li><a href="{% url 'user_logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
        {% endif %}
    </ul>
  </div>
</nav>
	
<body>

<div class="center-column">
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-{{message.tags}}">
				{{message}}				
			</div>
		{% endfor %}
	{% endif %}

    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

hw3_to_do/to_do/templates/to_do/home.html
{% extends 'to_do/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

	<div class="todo-list">
	<h2>My ToDo List</h2>

		<!-- here is set up the task -->	
		{% for task in tasks %}
		<div class="item-row">
			<!-- this a tag is for task special view -->
			<p><a href="{% url 'to_do_view' task.id %}">
			<span>{{ task.name }}</span>
			</a></p>
			<a class="btn btn-sm btn-info" href="{% url 'to_do_update' task.id %}">Update</a>
			<a class="btn btn-sm btn-danger" href="{% url 'task_delete' task.id %}">Delete</a>
			
		</div>
	{% endfor %}

		<div class="item-row">
				<!-- this is for create -->
				<a href="{% url 'to_do_create' %}"><button class="btn btn-success" type="submit" name="Create Task">Create</button></a>
		</div>



	</div>
{% endblock content %}

hw3_to_do/to_do/templates/to_do/new_task.html
{% extends 'to_do/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

		<h3>New Task</h3>
		<form method="POST" >
			{% csrf_token %}
			{{ form|crispy }}

			<input class="btn btn-info" type="submit" name="Create Task">
		</form>

{% endblock content %}

hw3_to_do/to_do/templates/to_do/task_update.html
{% extends 'to_do/base.html' %}
{% load crispy_forms_tags %}
	{% block content %}

		<h3>Update Task</h3>		
		<form method="POST" >
			{% csrf_token %}
			{{ form|crispy }}

			<input class="btn btn-info" type="submit" name="Update Task">
		</form>

	{% endblock content %}

hw3_to_do/to_do/templates/to_do/task_view.html
{% extends 'to_do/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="todo-list">
	<h2>Tasks</h2>

		<br>
		<h4><strong>{{task.name}}</strong></h4>
		<br>
		<h5><b>DESCRIPTION</b>> - {{task.description}}</h5>
		<h6><b>DATE TIME</b> - {{task.date_time}}</h6>
		<h6><b>NOTIFICATION</b> - {{task.get_notification_display}}</h6>
		<h6><b>STATUS</b> - {{task.get_status_display}}</h6>
		<br>	

	<a class="btn btn-sm btn-success" href="{% url 'home' %}">Back</a>
	<a class="btn btn-sm btn-info" href="{% url 'to_do_update' task.id %}">Update</a>
		<a class="btn btn-sm btn-danger" href="{% url 'task_delete' task.id %}">Delete</a>

	</div>
{% endblock content %}

hw3_to_do/to_do/templates/to_do/welcome.html
{% extends 'to_do/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

	
	<div class="todo-list">
	<h2>Hello Dear User 🙂</h2>

	<div class="item-row">				
		<h5>You are now in ToDo website where you can create your daily #ToDo_List, update them, turn on noticication and what deadline do you have for that task.</h5>
	</div>

	<div class="item-row">
		<h5>But before that please Log In below</h5>
		<a class="btn btn-sm btn-warning" href="{% url 'login' %}">Log In</a>
	</div>
	<div class="item-row">
		<h5>Need an Account?</h5>
		<a class="btn btn-sm btn-info" href="{% url 'register' %}">Sign Up</a>
	</div>	

	</div>
{% endblock content %}